--테이블생성
CREATE TABLE KOPO_PRODUCT_VOLUME_JM
(
REGIONID VARCHAR2(100),
PRODUCTID VARCHAR2(100),
YEARWEEK VARCHAR2(100),
QTY NUMBER,
EVENTCODE VARCHAR2(100),
constraints pk_kopo_product_volume_jm primary key (REGIONID, PRODUCTID, YEARWEEK),
constraints fk_kopo_product_volume_jm foreign key (EVENTCODE) references EVENT_MGMT (EVENT_ID)
)
--이벤트관리테이블
CREATE TABLE EVENT_MGMT
(
EVENT_ID VARCHAR2(100),
EVENT_PERIODS VARCHAR2(100),
DISCOUNT_PERCENT NUMBER),
constraint pk_event_mgmt primary key (EVENT_ID),
)


INSERT INTO EVENT_MGMT VALUES('EV0001','201502',0.3);


INSERT INTO EVENT_MGMT VALUES('EV0002','202103',0.5);