--112서버 내 "SORT_EXAMPLE" 테이블을 
--WEEK 별로 내림차순정렬하고 쿼리문을 작성하세요 
--SELECT * FROM SORT_EXAMPLE 포함하여 한줄로 쿼리를 작성하세요
SELECT * FROM SORT_EXAMPLE ORDER BY WEEK DESC

SELECT WEEK, 
LPAD(WEEK, 2, 0) 
FROM SORT_EXAMPLE 
ORDER BY LPAD(WEEK, 2, 0)DESC

--112번 서버에 접속한 후 KOPO_CHANNEL_SEASONALITY2 
--테이블에서 제품군별로 판매량을 집계한 후 
--TV, APS, MOBILE, REF, WM 순으로 정렬하는 쿼리를 작성하세요
SELECT DISTINCT PRODUCTGROUP
FROM KOPO_CHANNEL_SEASONALITY2
ORDER BY --TV, APS, MOBLIE, REF, WM
CASE WHEN PRODUCTGROUP='TV' THEN 0
    WHEN PRODUCTGROUP='APS' THEN 1
    WHEN PRODUCTGROUP='MOBLIE' THEN 3
    WHEN PRODUCTGROUP='REF' THEN 4 ELSE 5 END
    
--KOPO_CHANNEL_SEASNOALITY2 안에있는 REGIONID열의 
--A를 REGION_로 바꿔서 REGIONID_NEW라는 컬럼명으로 보기
SELECT
    REPLACE(A.REGIONID, 'A', 'REGION_') AS REGIONID_NEW,
    A.*
FROM KOPO_CHANNEL_SEASNOALITY2 A



SELECT
    ROUND(12.345,2),    --반올림
    CEIL(12.345),       --근접한큰정수
    FLOOR(12.345),      --근접한작은정수
    MOD(12,10),         --나누기후나머지
    POWER(3,2)          --3의2승
    FROM DUAL
    
-- RMSE_MAE_EXAMPLE2 테이블에서
-- MAPE ABSOLUTE PERCENTAGE ERROR ACCURACY = 
-- 1 - ABS(예측값-실제값) / 예측값 
-- 공식을 활용하여 정확도를 산출하세요 (소수점 2째자리 반올림)
SELECT  A.YEARWEEK,
        A.ACTUAL,
        A.FCST,
       ROUND((1 - ABS(A.FCST-A.ACTUAL) / A.FCST)*100,2) AS ACCURACY
FROM RMSE_MAE_EXAMPLE2 A
ORDER BY YEARWEEK ASC


SELECT A.*,
        --1(일), 2(월), 3(화), 4(수), 5(목), 6(금), 7(토)
        NEXT_DAY(SYSDATE,3)
FROM KOPO_CHANNEL_RESULT A
    


SELECT B.* FROM
(
    SELECT  REGIONID,
            PRODUCT,
            YEARWEEK,
            QTY, --1000미만 1000 1000 <= QTY < 10000 10000 30000
            CASE WHEN QTY < 1000 THEN 1000
                 WHEN QTY < 10000 THEN 10000
                 ELSE 30000 END AS QTY_NEW
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        WHERE 1=1
)B
WHERE 1=1
AND B.QTY >=1000
AND B.QTY < 10000
AND B.QTY_NEW != 10000


--다시보기
SELECT 
    YEARWEEK,
       CASE WHEN QTY<1000 THEN 1000
            WHEN QTY>1000 AND QTY <10000 THEN 10000
            ELSE 30000 END AS QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW