--“KOPO_PRODUCT_VOLUME” 테이블에서?
--201601주차 이상이면서?
--ST0001 상품 데이터를 조회하세요
SELECT A.*,
            A.VOLUME * 1.2 AS NEW_VOLUME
FROM KOPO_PRODUCT_VOLUME A
            



SELECT * FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0002'
AND YEARWEEK  >= '201515' AND YEARWEEK <= '201516'
-- └> AND YEARWEEK IN ('201515','201516') 이렇게 해도 됨

--KOPO_PROMOTION 불러오기
SELECT * FROM KOPO_PROMOTION

--임시로 테이블안에 NEW_PMAP이라는 컬럼을 추가하여 생성(AS 컬럼명)
--NEW_PMAP은 10%할인, 반올림(ROUND)
SELECT A.*,
            ROUND(A.PMAP * 0.9) AS NEW_PMAP
FROM KOPO_PROMOTION A

SELECT A.* 
FROM KOPO_PROMOTION A
WHERE 1=1
AND MAP_PRICE IS NULL

SELECT * FROM TABS
WHERE 1=1
AND TABLE

--KOPO_PRODUCT_VOLUME 테이블에서?
--연산자를 활용하여?
--‘ST0001’의 201544~201548 주차 실적만 조회하세요?
SELECT * FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN '201544' AND '201548'

--KOPO_PROMOTION 테이블에서?
--TARGETWEEK 컬럼에 대한 시작,종료 2개의?
--사용자 변수를 입력 받아 201501, 201503?
--사이 데이터를 조회하세요.
SELECT *
FROM KOPO_PROMOTION
WHERE TARGETWEEK = &START

--ASC오름차순정렬, DESC내림차순정렬
SELECT * FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
ORDER BY REGIONID, PRODUCTGROUP, YEARWEEK ASC

SELECT * FROM KOPO_PRODUCT_VOLUME
UNION --중복제거병합 (UNION ALL은 중복포함병합)
SELECT * FROM KOPO_PRODUCT_VOLUME

--소문자 대문자 변환
SELECT 
    LOWER(PRODUCTGROUP) AS JM1,
    UPPER(REGIONID) AS JM2
FROM KOPO_PRODUCT_VOLUME

--컬럼 값 합치기
SELECT CONCAT(REGIONID,CONCAT('_',PRODUCTGROUP))AS JM
FROM KOPO_PRODUCT_VOLUME


--컬럼 값 추출하기
SELECT PRODUCTGROUP,
SUBSTR(PRODUCTGROUP, 0, 2)
FROM KOPO_PRODUCT_VOLUME

--컬럼 값 채우기
SELECT REGIONID,
LPAD(REGIONID, 5, 0),
RPAD(REGIONID, 5, 'HI')
FROM KOPO_PRODUCT_VOLUME

--KOPO_CUSTOMERDATA의 고객코드는 10자리이다
--만약 10자리가아니면 왼쪽에0으로 채운다
--이후 고객코드의 뒷4자리는
--암호화를위해 * 처리를해야합니다.


SELECT CUSTOMERCODE,
LPAD(CUSTOMERCODE, 10, 0)
FROM KOPO_CUSTOMERDATA

