--테이블생성
CREATE TABLE TT
(
아이디 VARCHAR2(100),
도시개발사 VARCHAR2(100),
위치 VARCHAR2(100)
)
--테이블추가
INSERT INTO TT(아이디, 도시개발사, 위치) VALUES('A02', '카울팀', '구로')
--데이터삭제
DELETE FROM TT WHERE 아이디 = 'A02'
--테이블삭제
DROP TABLE TT
--테이블전체조회
SELECT * FROM TT


--NVL처리 (NULL값을 때 입력한 값('0')으로 치환)
SELECT REGIONID,
        YEARWEEK,
        NVL(VOLUME,0) AS VOLUME
        NVL2(VOLUME, VOLUME, 1) AS VOLUME
FROM NVL_CHECK



SELECT A.GENDER,
        UPPER(A.GENDER) AS GENDER_NEW,
         DECODE(
            UPPER(A.GENDER),'MALE',1,0)
FROM KOPO_CUSTOMERDATA A




-- DT_RESULT_FINAL3 테이블에서정확도를산출하세요
-- 단, 예측값이0인경우정확도는0
-- 정확도= 1-ABS(예측값-실측값)/예측값
SELECT * FROM DT_RESULT_FINAL3

SELECT A.* ,
        CASE WHEN PREDICTION_QTY = 0 THEN 0
        ELSE ROUND((1 - ABS(PREDICTION_QTY-REAL_QTY) / PREDICTION_QTY)*100,2) END AS 정확도
FROM DT_RESULT_FINAL3 A




SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW

--A60지역에 판매되는 모든 상품을 기준으로
--A01, A02 지역에서 언제 출시되었고 언제까지 팔리고 있는지를 알아본다.
SELECT REGIONID,
       PRODUCT,
        MIN(YEARWEEK) AS LAUNCH_DATE, --출시일
        MAX(YEARWEEK) AS LAST_DATE    --최종거래일
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND REGIONID IN ('A01','A02','A60')
AND PRODUCT IN (SELECT DISTINCT PRODUCT
                FROM KOPO_CHANNEL_SEASONALITY_NEW
                WHERE REGIONID = 'A60')
GROUP BY REGIONID, PRODUCT --그룹키
HAVING MIN(YEARWEEK) > 201401



SELECT * FROM GROUP_TEST

SELECT 지역, 상품,
   SUM(거래량) AS 거래총량 --SUM, MIN, MAX, AVG 중 가능
FROM GROUP_TEST
GROUP BY 지역, 상품